spring:
 profiles:
   action:
   - dev
---
server:
 port: 8201
spring:
 profiles: dev
 application:
   name: microservicecloud_config_client
eureka:
 client:
   service-url:
     defaultZone: http://eureka_dev.com:7001/eureka/
---
server:
 port: 8202
spring:
 profiles: test
 application:
   name: microservicecloud_config_client
eureka:
 client:
   service-url:
     defaultZone: http://eureka_test.com:7001/eureka/
